### ISSUE TITLE
Why do we run the containers as root?

### ISSUE THREAD

**Issue by noah-weingarden** [eecs485staff/ag-docker-images#36]
All of the project Dockerfiles have `USER root:root` as their last instruction. I don't think this is a best practice. Any ideas why we've been doing this?

**Comment by awdeorio** [comment]
I think @MattyMay might have expounded on this in another thread that I can't seem to find at the moment.

**Comment by noah-weingarden** [comment]
Nah, autograder.io's docs don't have any information on this; the only source is the readme of [this repo](https://github.com/eecs-autograder/base-docker-images). Since I don't have autograder access I can't find out what would happen if you didn't enter as root. Now that we've changed the `docker-run` scripts to run as `autograder` though, this question is reduced to idle curiosity.

**Comment by MattyMay** [comment]
Autograder infra uses a command runner program that is run as root to execute commands within the container, so the images need to be created with USER root as the last user directive. The runner (unless specified otherwise) runs the commands as subprocesses as the autograder user.

This was from a quick read through of the [repo](https://github.com/eecs-autograder/autograder-sandbox) and I didn't read closely enough to figure out exactly why it needs to run the command runner as root, but that's the idea.

**Comment by noah-weingarden** [comment]
Ah, cool! Thanks for investigating!
